spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:env}

  config:
    import: optional:file:.env[.properties]

server:
  port: ${PORT:8080}

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method

# Logging
logging:
  level:
    org.springdoc: INFO
    org.springframework.web: INFO
